### ISSUE TITLE
Using THREE.js?

### ISSUE THREAD

**Issue by senart** [react-community/react-native-webgl#12]
You say that we can use a 
> ...preferred library, like...https://github.com/mrdoob/three.js... 

How would one go about implementing this? Thanks!

**Comment by gre** [comment]
most webgl libs accept a WebGLContext, so you can basically use any webgl lib with react-native-webgl by giving the context (that you get in onContextCreate https://github.com/react-community/react-native-webgl/blob/master/example/App.js#L7 )

We'll have to write some more examples in the future
for Three.js for now see https://github.com/react-community/react-native-webgl/issues/6

**Comment by robertjuh** [comment]
The doesnt seem to work
i Replaced it with: https://github.com/react-community/react-native-webgl/tree/master/example

But there is no App.js to be found

tried to find out what App means in the example, saw that the 6 examples (like ThreeCube) are exported as: "export default class App extends React.Component". 

Been puzzling the entire day how to get this in my own app, all i get is a square with a white background(thats because i styled the WebGLView like that) and a 1pixel wide red line on the left of it(which i dont understand).

```
		glView: {
			width: 250,
			height: 250,
			backgroundColor: '#fff'	
		}
```
Might be that it doesnt work because i'm using other version of react native because of compatibility with viro react

**Comment by robertjuh** [comment]
oncontextcreate will now execute when i call it like this:

```
<WebGLView style={styles.glView}>						
	{this.onContextCreate()}						
</WebGLView>	
```

But 'gl' is undefined so it still doesn't work

**Comment by robertjuh** [comment]
Nevermind this reply^ i'll make a new issue for it
