### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by TheCodeDestroyer** [react-community/react-native-webgl#78]
I think title should be enough, but just in case what I mean by that is if this library is still being worked on? I see there hasnt been any activity on for at least a year...

P.S.: Im not trying be a jerk or anything I'm just wondering if there is a project out there that is more actively  maintained and is meant to replace this one?

**Comment by gre** [comment]
this project was forked 1-2 years ago from Expo EXGLView as an attempt to be the common base implementation that would be used by Expo & gl-react-native & any other lib that want a WebGL implementation in React Native ecosystem. This is why it was made part of react-community initially.

In practice, this did not happen: Expo still maintains its own version and don't backport the changes here. I guess it's not that trivial to have this being a dependency and I don't blame them, because they have many building blocks to make everything works together so it's easier to just have the implementation embedded (like for instance, GLView support interoperability with Camera, Video, and other cool stuff like VR). In react-native-webgl implementation attempt, I was imagining things could still work in a loosely coupled way (this is the idea of the "RN" extension and the Texture Config formats) so in theory it works but it needs time to implement it in Expo and convince people. Since then the Expo EXGLView implementation have also diverged.

On my side, I have near to zero time to maintain this project. 😭

**Comment by TheCodeDestroyer** [comment]
@gre thank you for this awesome reply. I just stumbled on your blog post for `gl-react` v3 I see that your plan is to do what Expo did for react native, is that correct? And if I understand that correctly that means that three.js could be used as well?

**Comment by gre** [comment]
- gl-react is opinionated in solving a subset of problem with fragment shaders.
- react-native-webgl is a generic implementation of WebGL, you can do whatever you can do with WebGL, like using a library like three.js.

Expo implements EXGLView that is literally this. react-native-webgl is just a fork of this little part of Expo.

**Comment by TheCodeDestroyer** [comment]
Alright thank you for all your info!

**Comment by dixitcy** [comment]
@TheCodeDestroyer . Did you find a better alternative for gl stuff in react native ?

**Comment by TheCodeDestroyer** [comment]
I managed to setup react native with expo-core which is somewhat less bloated, but there was so much pain with that so I decided to go with Unity instead, but if you're interested here are some links:
- [Expo Core](https://github.com/expo/expo/tree/master/packages/expo-core)
- [Expo GL](https://github.com/expo/expo/tree/master/packages/expo-gl)
